[package]
name = "xpic-cli"
version = "0.1.1"
edition = "2021"
description = "Save wallpapers from Windows Spotlight and Bing"

[dependencies]
xpic = { path = "../xpic" }
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
tokio = { version = "1.40", features = ["full"] }
