[package]
name = "xpic-cli"
version = "0.2.0"
edition = "2024"
description = "Save wallpapers from Windows Spotlight and Bing"

[dependencies]
xpic = { path = "../xpic" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.44", features = ["full"] }
