[package]
name = "xpic-cli"
version = "0.2.0"
edition = "2021"
description = "Save wallpapers from Windows Spotlight and Bing"

[dependencies]
xpic = { path = "../xpic" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
regex = "1.11"
url = "2.5"
