[package]
name = "xpic-cli"
version = "0.1.0"
edition = "2021"
description = "Save wallpapers from Windows Spotlight and Bing"

[dependencies]
xpic = { path = "../xpic" }
clap = { version = "4.5.1", features = ["derive"] }
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
