version: "3"

tasks:
  build-web:
    dir: xpic-web
    cmds:
      - pnpm build

  dev-web:
    dir: xpic-web
    cmds:
      - pnpm dev

  check-web:
    dir: xpic-web
    cmds:
      - pnpm check

  format-web:
    dir: xpic-web
    cmds:
      - pnpm format

  build:
    cmds:
      - cargo tauri build

  dev:
    cmds:
      - cargo tauri dev
