version: 3

tasks:
  format:
    cmd: rye fmt

  check:
    cmd: rye lint

  sync:
    cmd: rye sync

  list:
    cmd: rye run xpic-cli list

  save:
    cmd: rye run xpic-cli save

  run:
    cmd: rye run xpic

  gen:
    cmds:
      - rye run python assets/gen_ico.py
    sources:
      - assets/xpic.png
      - assets/gen_ico.py
    generates:
      - assets/xpic.ico

  bundle-cli:
    deps:
      - gen
    cmds:
      - rye run pyinstaller --onefile --name=xpic-cli --icon=assets/xpic.ico xpic_cli/__main__.py

  bundle-gui:
    deps:
      - gen
    cmds:
      - poetry run pyinstaller --add-data "assets/xpic.png:assets"  --add-data "assets/xpic.qss:assets" --onefile --name=xpic --icon=assets/xpic.ico --windowed xpic_gui/__main__.py

  bundle:
    deps:
      - bundle-cli
      - bundle-gui
