version: "3"

includes:
  web:
    taskfile: xpic-web/Taskfile.yaml
    dir: xpic-web

  cli:
    taskfile: xpic-cli/Taskfile.yaml
    dir: xpic-cli

tasks:
  setup:
    deps:
      - task: web:setup
    cmds:
      - cargo install tauri-cli

  build:
    dir: xpic-tauri
    cmds:
      - cargo tauri build

  debug:
    dir: xpic-tauri
    cmds:
      - cargo tauri build --debug

  dev:
    dir: xpic-tauri
    cmds:
      - cargo tauri dev
