# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  web:
    taskfile: web/Taskfile.yaml
    dir: web

  cli:
    taskfile: xpic-cli/Taskfile.yaml
    dir: xpic-cli

tasks:
  setup:
    deps:
      - task: web:setup
    cmds:
      - cargo install tauri-cli

  build:
    dir: app
    cmds:
      - cargo tauri build

  debug:
    dir: app
    cmds:
      - cargo tauri build --debug

  dev:
    dir: app
    cmds:
      - cargo tauri dev
