# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  web:
    taskfile: web/Taskfile.yaml
    dir: web

  cli:
    taskfile: crates/xpic/Taskfile.yaml
    dir: crates/xpic

  app:
    taskfile: app/Taskfile.yaml
    dir: app

tasks:
  setup:
    deps:
      - task: web:setup
      - task: app:setup

  build:
    deps:
      - task: cli:build
      - task: app:build
