version: "3"

tasks:
  setup-tauri:
    cmds:
      - cargo install tauri-cli

  setup-web:
    dir: xpic-web
    cmds:
      - bun install

  setup:
    deps:
      - setup-tauri
      - setup-web

  build-web:
    dir: xpic-web
    cmds:
      - bun run build

  dev-web:
    dir: xpic-web
    cmds:
      - bun run dev

  ui-add:
    dir: xpic-web
    cmds:
      - bun shadcn-svelte add {{.CLI_ARGS}}

  build-cli:
    cmds:
      - cargo build --manifest-path=xpic-cli/Cargo.toml {{.CLI_ARGS}}

  build:
    cmds:
      - cargo tauri build

  dev:
    cmds:
      - cargo tauri dev
