# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  web:
    taskfile: web/Taskfile.yaml
    dir: web

  cli:
    taskfile: crates/xpic/Taskfile.yaml
    dir: crates/xpic

  app:
    taskfile: app/Taskfile.yaml
    dir: app

tasks:
  setup:
    deps:
      - task: web:setup
      - task: app:setup

  build:
    deps:
      - task: app:build

  dev:
    deps:
      - task: app:dev

  release:
    cmds:
      - task: cli:build
      - nu -c "mkdir bin; mv target/release/xpic.exe bin/xpic-cli.exe"
      - task: app:build
      - nu -c "mv target/release/Xpic.exe bin; mv target/release/bundle/msi/*.msi bin; mv target/release/bundle/nsis/*.exe bin;"
