version: 3

tasks:
  format:
    cmd: poetry run ruff format .

  check:
    cmd: poetry run ruff check .

  list:
    cmd: poetry run python xpic-cli.py list

  save:
    cmd: poetry run python xpic-cli.py save

  run:
    cmd: poetry run python xpic.py

  gen:
    cmds:
      - poetry run python assets/gen_ico.py

  bundle-cli:
    deps:
      - gen
    cmds:
      - poetry run pyinstaller --onefile --icon=assets/xpic.ico xpic-cli.py

  bundle-gui:
    deps:
      - gen
    cmds:
      - poetry run pyinstaller --add-data "assets/xpic.png:assets"  --add-data "assets/xpic.qss:assets" --onefile --icon=assets/xpic.ico --windowed xpic.py

  bundle:
    deps:
      - bundle-cli
      - bundle-gui
