# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  app:
    taskfile: crates/xpic-app/Taskfile.yaml
    dir: crates/xpic-app

  cli:
    taskfile: crates/xpic/Taskfile.yaml
    dir: crates/xpic

  spotlight:
    taskfile: crates/spotlight/Taskfile.yaml
    dir: crates/spotlight

tasks:
  build:
    deps:
      - task: cli:build
      - task: spotlight:build

  release:
    deps:
      - task: build
    cmds:
      - nu -c "mkdir bin; mv target/release/xpic.exe bin/xpic-cli.exe"
      - nu -c "mv target/release/xpic-app.exe bin/Xpic.exe"
