set shell := ["nu", "-c"]
set script-interpreter := ["nu"]
set indentation := "  "
set default-list := true
set fallback

run *args:
  cargo run {{args}}

build *args:
  cargo build {{args}}

install:
  cargo install --path .
