[package]
name = "xpic-tauri"
version = "0.2.0-alpha.2"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
xpic = { path = "../xpic" }
tauri = { version = "2.0.0-beta.19", features = ["protocol-asset"] }
tauri-plugin-shell = "2.0.0-beta.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3.30"
glob = "0.3.1"
window-vibrancy = "0.5.0"
tauri-plugin-fs = "2.0.0-beta.7"
tauri-plugin-dialog = "2.0.0-beta.7"

[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
