[package]
name = "xpic-tauri"
version = "0.2.0-alpha.1"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
xpic = { path = "../xpic" }
tauri = { version = "1.6.0", features = [ "fs-copy-file", "dialog-save", "shell-open", "path-all", "window-center", "window-set-min-size", "window-set-size", "protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
glob = "0.3.1"
window-vibrancy = "0.4.3"

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
