[package]
name = "xpic-tauri"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
xpic = { path = "../xpic" }
tauri = { version = "1.6.0", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
glob = "0.3.1"
window-vibrancy = "0.4.3"

[features]
custom-protocol = ["tauri/custom-protocol"]
