name: Release

on:
  push:
    tags: ["v*.*.*"]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs: 
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Set up Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install

      - name: Bundle
        run: |
          poetry run python assets/gen_ico.py
          poetry run pyinstaller --onefile --icon=assets/xpic.ico xpic-cli.py
          poetry run pyinstaller --add-data "assets/xpic.png:assets"  --add-data "assets/xpic.qss:assets" --onefile --icon=assets/xpic.ico --windowed xpic.py

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/xpic-cli.exe
            dist/xpic.exe
