name: Release

on:
  push:
    tags: ["v*.*.*"]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs: 
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Task
        uses: arduino/setup-task@v2
      
      - name: Set up Rye
        uses: eifinger/setup-rye@v4

      - name: Bundle
        run: task bundle

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/xpic-cli.exe
            dist/xpic.exe
